# basically, ci but on a matrix.
# only built if requested (via try) or for merges
name: ci for merge
on:
  push:
    branches:
      - trying
      - staging

jobs:
  ci-merge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          # beta is run as part of `ci.yml`
          - nightly
          - 1.38.0  # MSRV

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --all-targets --all-features --verbose

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-targets --all-features --verbose
